# optional
# template: default

# required
language: cs_CZ


title: blog - Pavel Prchal

# optional
#rootDir: z:\Shared\fruitfly\FruitFly
rootDir: c:\Users\Pavel\Documents\fruitfly\FruitFly
#rootDir: c:\Data\Shared\fruitfly\FruitFly