# optional
# template: default

# required
language: cs_CZ


title: blog - Pavel Prchal

# optional
rootDir: c:\Users\Pavel\Documents\fruitfly\FruitFly\
workDir: c:\Users\Pavel\Desktop\pavel.borec.cz\