# Configuration flie
# ~o~

# default template - change if you want {config:template}
template: default

# pick your language {config:language}
language: cs_CZ

# blog title accessed ad {config:title}
title: blog - Pavel Prchal

# blog home url
home: http://pavel.borec.cz
